### ISSUE TITLE
[Question]: 在mac上运行自带的压测代码，antspool的并发不如原生的goroutine

### ISSUE THREAD

**Issue by coder-dalinge** [panjf2000/ants#314] opened 2024-02-02 03:48 UTC
### Questions with details

![F05D0348-8360-4FF4-B58F-3344E3F608DF](https://github.com/panjf2000/ants/assets/78412696/4c7e3536-4c48-49f5-9c7f-3605ed5a166e)

**Comment by panjf2000** [comment] 2024-02-02 04:57
Duplicate of #166

**Closed by panjf2000** 2024-02-02 04:57 UTC
Labels: help wanted, question
